# This is a basic workflow to help you get started with Actions



# Controls when the workflow will run


name: Ansible folder
on:
  push:
    paths:
      - 'ansible/**'
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  handle-api:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "ansible folder changed!"
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "My first deploy step"
        run: echo "Deplyment Complete"          
